In [39]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [25, 30, 35, 40, 45],
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "blood_type": ["A", "B", "O", "AB", "A"],
    "exam_marks": [23,54,23,11,67]
    
}
df = pd.DataFrame(data)


# df.to_csv('people.csv', index=False)  #--> it will same the csv file, index=False means the index will not be saved in the csv file and viceversa with true
 
print("Display first 5 row")
print(df.head(2))

print("Display last 2 row")
print(df.tail(2))

Display first 5 row
    name  age         city blood_type  exam_marks
0  Alice   25     New York          A          23
1    Bob   30  Los Angeles          B          54
Display last 2 row
    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [40]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   age         5 non-null      int64
 2   city        5 non-null      object
 3   blood_type  5 non-null      object
 4   exam_marks  5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes
None

In [41]:
df.describe()

             age  exam_marks
count   5.000000    5.000000
mean   35.000000   35.600000
std     7.905694   23.702321
min    25.000000   11.000000
25%    30.000000   23.000000
50%    35.000000   23.000000
75%    40.000000   54.000000
max    45.000000   67.000000

In [42]:
print(f"Dataset shape:  {df.shape}")
print(f"Column names: {df.columns}")
print(f"Dataset info: {df.info}")

Dataset shape:  (5, 5)
Column names: Index(['name', 'age', 'city', 'blood_type', 'exam_marks'], dtype='object')
Dataset info: <bound method DataFrame.info of       name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67>

In [43]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks']]

      name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67

In [44]:
high_age = df[  (df['age'] >= 40)   ]

In [45]:
print(high_age)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [46]:
useless = df[  (df['age'] >= 40)  &  (df['exam_marks'] <= 20)  ]

In [47]:
print(useless)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11

In [48]:
blood_a = df[ (df['age'] >= 20)   &    (df['blood_type'] == "A")]

In [49]:
print(blood_a)

    name  age      city blood_type  exam_marks
0  Alice   25  New York          A          23
4    Eva   45   Phoenix          A          67

In [50]:
print(df)

      name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67

In [51]:
df['real_age']= df.age + 1

In [52]:
print(df)   #6: 07

      name  age         city blood_type  exam_marks  real_age
0    Alice   25     New York          A          23        26
1      Bob   30  Los Angeles          B          54        31
2  Charlie   35      Chicago          O          23        36
3    David   40      Houston         AB          11        41
4      Eva   45      Phoenix          A          67        46

In [53]:
#adding column by insert method
df.insert(6, "Person_behaviour", ["happy", "sad", "angry", "confused", "paranoid"])

In [54]:
print(df)

      name  age         city blood_type  exam_marks  real_age Person_behaviour
0    Alice   25     New York          A          23        26            happy
1      Bob   30  Los Angeles          B          54        31              sad
2  Charlie   35      Chicago          O          23        36            angry
3    David   40      Houston         AB          11        41         confused
4      Eva   45      Phoenix          A          67        46         paranoid

In [55]:
print(df)

      name  age         city blood_type  exam_marks  real_age Person_behaviour
0    Alice   25     New York          A          23        26            happy
1      Bob   30  Los Angeles          B          54        31              sad
2  Charlie   35      Chicago          O          23        36            angry
3    David   40      Houston         AB          11        41         confused
4      Eva   45      Phoenix          A          67        46         paranoid

In [56]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour'],
      dtype='object')

In [57]:
df.loc[0, 'Peoples_id'] = 55

In [58]:
df

,name,age,city,blood_type,exam_marks,real_age,Person_behaviour,Peoples_id
0,Alice,25,New York,A,23,26,happy,55.0
1,Bob,30,Los Angeles,B,54,31,sad,NaN
2,Charlie,35,Chicago,O,23,36,angry,NaN
3,David,40,Houston,AB,11,41,confused,NaN
4,Eva,45,Phoenix,A,67,46,paranoid,NaN

In [59]:
df.loc[0, 'Peoples_id'] = 1

In [60]:
print(df)

      name  age         city blood_type  exam_marks  real_age  \
0    Alice   25     New York          A          23        26
1      Bob   30  Los Angeles          B          54        31
2  Charlie   35      Chicago          O          23        36
3    David   40      Houston         AB          11        41
4      Eva   45      Phoenix          A          67        46

  Person_behaviour  Peoples_id
0            happy         1.0
1              sad         NaN
2            angry         NaN
3         confused         NaN
4         paranoid         NaN

In [61]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour', 'Peoples_id'],
      dtype='object')

In [62]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1.0,Alice,25,New York,A,23,26,happy
1,NaN,Bob,30,Los Angeles,B,54,31,sad
2,NaN,Charlie,35,Chicago,O,23,36,angry
3,NaN,David,40,Houston,AB,11,41,confused
4,NaN,Eva,45,Phoenix,A,67,46,paranoid

In [63]:
df.loc[0, 'name'] = "Shrabin"

# example with row 
#df.loc['d'] = ['6', 'Shrabin', 20]# etc

In [64]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1.0,Shrabin,25,New York,A,23,26,happy
1,NaN,Bob,30,Los Angeles,B,54,31,sad
2,NaN,Charlie,35,Chicago,O,23,36,angry
3,NaN,David,40,Houston,AB,11,41,confused
4,NaN,Eva,45,Phoenix,A,67,46,paranoid

In [65]:
df.loc[0, 'age'] = 20
df.loc[0, 'city'] = "Kathmandu"
df.loc[0, 'blood_type'] = "O+"
df.loc[0, 'exam_marks'] = 78
df.loc[0, 'real_age'] = 21
df.loc[0, 'Person_behaviour' ] = "Excited"

In [66]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1.0,Shrabin,20,Kathmandu,O+,78,21,Excited
1,NaN,Bob,30,Los Angeles,B,54,31,sad
2,NaN,Charlie,35,Chicago,O,23,36,angry
3,NaN,David,40,Houston,AB,11,41,confused
4,NaN,Eva,45,Phoenix,A,67,46,paranoid

In [67]:
df.insert(7, "race", ["Brown", " White", "White", "Asian", "Black"])

In [68]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour', 'race', 'Peoples_id'],
      dtype='object')

In [69]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour', 'race']]

,name,age,city,blood_type,exam_marks,real_age,Person_behaviour,race
0,Shrabin,20,Kathmandu,O+,78,21,Excited,Brown
1,Bob,30,Los Angeles,B,54,31,sad,White
2,Charlie,35,Chicago,O,23,36,angry,White
3,David,40,Houston,AB,11,41,confused,Asian
4,Eva,45,Phoenix,A,67,46,paranoid,Black

In [70]:
df.loc[0, 'blood_type'] = "O+"

In [71]:
print(df)

      name  age         city blood_type  exam_marks  real_age  \
0  Shrabin   20    Kathmandu         O+          78        21
1      Bob   30  Los Angeles          B          54        31
2  Charlie   35      Chicago          O          23        36
3    David   40      Houston         AB          11        41
4      Eva   45      Phoenix          A          67        46

  Person_behaviour    race  Peoples_id
0          Excited   Brown         1.0
1              sad   White         NaN
2            angry   White         NaN
3         confused   Asian         NaN
4         paranoid   Black         NaN

In [72]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour', 'race', 'Peoples_id'],
      dtype='object')

In [73]:
#replacing the value of multiple row at once.
df.loc[0, ['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age', 'Person_behaviour', 'race']] = ["Shrabin", 20, "Kathmandu", "O+", 67, 21, "Charming", "Brown"]

In [74]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks', 'real_age',
       'Person_behaviour', 'race']]

,name,age,city,blood_type,exam_marks,real_age,Person_behaviour,race
0,Shrabin,20,Kathmandu,O+,67,21,Charming,Brown
1,Bob,30,Los Angeles,B,54,31,sad,White
2,Charlie,35,Chicago,O,23,36,angry,White
3,David,40,Houston,AB,11,41,confused,Asian
4,Eva,45,Phoenix,A,67,46,paranoid,Black

In [75]:
#removing the column real_age from the data
#method no.1
# a = df.drop(columns= 'real_age')

#method no.2
df.drop(columns='real_age', inplace=True)

#method no.3
#df.drop('real_age', axis = 1)

In [38]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'Person_behaviour',
       'race'],
      dtype='object')

In [76]:
#increasing the age by 1, in seperate column
df['real_age'] = df['age'] + 1

In [78]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks', 'Person_behaviour',
       'race', 'Peoples_id', 'real_age']]

,name,age,city,blood_type,exam_marks,Person_behaviour,race,Peoples_id,real_age
0,Shrabin,20,Kathmandu,O+,67,Charming,Brown,1.0,21
1,Bob,30,Los Angeles,B,54,sad,White,NaN,31
2,Charlie,35,Chicago,O,23,angry,White,NaN,36
3,David,40,Houston,AB,11,confused,Asian,NaN,41
4,Eva,45,Phoenix,A,67,paranoid,Black,NaN,46

In [79]:
df.drop('real_age', axis = 1, inplace= True)

In [80]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks', 'Person_behaviour',
       'race', 'Peoples_id'],
      dtype='object')

In [82]:
df.drop('Peoples_id', axis = 1, inplace= True)

In [85]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks', 'Person_behaviour', 'race']]

      name  age         city blood_type  exam_marks Person_behaviour    race
0  Shrabin   20    Kathmandu         O+          67         Charming   Brown
1      Bob   30  Los Angeles          B          54              sad   White
2  Charlie   35      Chicago          O          23            angry   White
3    David   40      Houston         AB          11         confused   Asian
4      Eva   45      Phoenix          A          67         paranoid   Black

Data Cleaning