In [54]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [25, 30, 35, 40, 45],
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "blood_type": ["A", "B", "O", "AB", "A"],
    "exam_marks": [23,54,23,11,67]
    
}
df = pd.DataFrame(data)


# df.to_csv('people.csv', index=False)  #--> it will same the csv file, index=False means the index will not be saved in the csv file and viceversa with true
 
print("Display first 5 row")
print(df.head(2))

print("Display last 2 row")
print(df.tail(2))

Display first 5 row
    name  age         city blood_type  exam_marks
0  Alice   25     New York          A          23
1    Bob   30  Los Angeles          B          54
Display last 2 row
    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [55]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   age         5 non-null      int64
 2   city        5 non-null      object
 3   blood_type  5 non-null      object
 4   exam_marks  5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes
None

In [56]:
df.describe()

             age  exam_marks
count   5.000000    5.000000
mean   35.000000   35.600000
std     7.905694   23.702321
min    25.000000   11.000000
25%    30.000000   23.000000
50%    35.000000   23.000000
75%    40.000000   54.000000
max    45.000000   67.000000

In [70]:
print(f"Dataset shape:  {df.shape}")
print(f"Column names: {df.columns}")
print(f"Dataset info: {df.info}")

Dataset shape:  (5, 5)
Column names: Index(['name', 'age', 'city', 'blood_type', 'exam_marks'], dtype='object')
Dataset info: <bound method DataFrame.info of       name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67>

In [81]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks']]

      name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67

In [94]:
high_age = df[  (df['age'] >= 40)   ]

In [95]:
print(high_age)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [ ]:
useless = df[  (df['age'] >= 40)  &  (df['exam_marks'] <= 20)  ]

In [97]:
print(useless)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11

In [103]:
blood_a = df[ (df['age'] >= 20)   &    (df['blood_type'] == "A")]

In [ ]:
print(blood_a)

#hello

    name  age      city blood_type  exam_marks
0  Alice   25  New York          A          23
4    Eva   45   Phoenix          A          67