In [1]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [25, 30, 35, 40, 45],
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "blood_type": ["A", "B", "O", "AB", "A"],
    "exam_marks": [23,54,23,11,67]
    
}
df = pd.DataFrame(data)


# df.to_csv('people.csv', index=False)  #--> it will same the csv file, index=False means the index will not be saved in the csv file and viceversa with true
 
print("Display first 5 row")
print(df.head(2))

print("Display last 2 row")
print(df.tail(2))

Display first 5 row
    name  age         city blood_type  exam_marks
0  Alice   25     New York          A          23
1    Bob   30  Los Angeles          B          54
Display last 2 row
    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [2]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   age         5 non-null      int64
 2   city        5 non-null      str
 3   blood_type  5 non-null      str
 4   exam_marks  5 non-null      int64
dtypes: int64(2), str(3)
memory usage: 332.0 bytes
None

In [3]:
df.describe()

             age  exam_marks
count   5.000000    5.000000
mean   35.000000   35.600000
std     7.905694   23.702321
min    25.000000   11.000000
25%    30.000000   23.000000
50%    35.000000   23.000000
75%    40.000000   54.000000
max    45.000000   67.000000

In [4]:
print(f"Dataset shape:  {df.shape}")
print(f"Column names: {df.columns}")
print(f"Dataset info: {df.info}")

Dataset shape:  (5, 5)
Column names: Index(['name', 'age', 'city', 'blood_type', 'exam_marks'], dtype='str')
Dataset info: <bound method DataFrame.info of       name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67>

In [5]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks']]

      name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67

In [6]:
high_age = df[  (df['age'] >= 40)   ]

In [7]:
print(high_age)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11
4    Eva   45  Phoenix          A          67

In [8]:
useless = df[  (df['age'] >= 40)  &  (df['exam_marks'] <= 20)  ]

In [9]:
print(useless)

    name  age     city blood_type  exam_marks
3  David   40  Houston         AB          11

In [10]:
blood_a = df[ (df['age'] >= 20)   &    (df['blood_type'] == "A")]

In [11]:
print(blood_a)

    name  age      city blood_type  exam_marks
0  Alice   25  New York          A          23
4    Eva   45   Phoenix          A          67

In [12]:
print(df)

      name  age         city blood_type  exam_marks
0    Alice   25     New York          A          23
1      Bob   30  Los Angeles          B          54
2  Charlie   35      Chicago          O          23
3    David   40      Houston         AB          11
4      Eva   45      Phoenix          A          67

In [13]:
df['real_age']= df.age + 1

In [14]:
print(df)   #6: 07

      name  age         city blood_type  exam_marks  real_age
0    Alice   25     New York          A          23        26
1      Bob   30  Los Angeles          B          54        31
2  Charlie   35      Chicago          O          23        36
3    David   40      Houston         AB          11        41
4      Eva   45      Phoenix          A          67        46

In [22]:
#adding column by insert method
df.insert(7, "Person_behaviour", ["happy", "sad", "angry", "confused", "paranoid"])

In [17]:
print(df)

   Peoples_id     name  age         city blood_type  exam_marks  real_age
0           1    Alice   25     New York          A          23        26
1           2      Bob   30  Los Angeles          B          54        31
2           3  Charlie   35      Chicago          O          23        36
3           4    David   40      Houston         AB          11        41
4           5      Eva   45      Phoenix          A          67        46

In [23]:
print(df)

   Peoples_id     name  age         city blood_type  exam_marks  real_age  \
0           1    Alice   25     New York          A          23        26
1           2      Bob   30  Los Angeles          B          54        31
2           3  Charlie   35      Chicago          O          23        36
3           4    David   40      Houston         AB          11        41
4           5      Eva   45      Phoenix          A          67        46

  Person_behaviour
0            happy
1              sad
2            angry
3         confused
4         paranoid

In [25]:
df.columns

Index(['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour'],
      dtype='str')

In [26]:
df.loc[0, 'Peoples_id'] = 55

In [27]:
df

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,55,Alice,25,New York,A,23,26,happy
1,2,Bob,30,Los Angeles,B,54,31,sad
2,3,Charlie,35,Chicago,O,23,36,angry
3,4,David,40,Houston,AB,11,41,confused
4,5,Eva,45,Phoenix,A,67,46,paranoid

In [28]:
df.loc[0, 'Peoples_id'] = 1

In [29]:
print(df)

   Peoples_id     name  age         city blood_type  exam_marks  real_age  \
0           1    Alice   25     New York          A          23        26
1           2      Bob   30  Los Angeles          B          54        31
2           3  Charlie   35      Chicago          O          23        36
3           4    David   40      Houston         AB          11        41
4           5      Eva   45      Phoenix          A          67        46

  Person_behaviour
0            happy
1              sad
2            angry
3         confused
4         paranoid

In [30]:
df.columns

Index(['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour'],
      dtype='str')

In [31]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1,Alice,25,New York,A,23,26,happy
1,2,Bob,30,Los Angeles,B,54,31,sad
2,3,Charlie,35,Chicago,O,23,36,angry
3,4,David,40,Houston,AB,11,41,confused
4,5,Eva,45,Phoenix,A,67,46,paranoid

In [33]:
df.loc[0, 'name'] = "Shrabin"

In [34]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1,Shrabin,25,New York,A,23,26,happy
1,2,Bob,30,Los Angeles,B,54,31,sad
2,3,Charlie,35,Chicago,O,23,36,angry
3,4,David,40,Houston,AB,11,41,confused
4,5,Eva,45,Phoenix,A,67,46,paranoid

In [35]:
df.loc[0, 'age'] = 20
df.loc[0, 'city'] = "Kathmandu"
df.loc[0, 'blood_type'] = "O+"
df.loc[0, 'exam_marks'] = 78
df.loc[0, 'real_age'] = 21
df.loc[0, 'Person_behaviour' ] = "Excited"

In [38]:
df[['Peoples_id', 'name', 'age', 'city', 'blood_type', 'exam_marks',
       'real_age', 'Person_behaviour']]

,Peoples_id,name,age,city,blood_type,exam_marks,real_age,Person_behaviour
0,1,Shrabin,20,Kathmandu,O+,78,21,Excited
1,2,Bob,30,Los Angeles,B,54,31,sad
2,3,Charlie,35,Chicago,O,23,36,angry
3,4,David,40,Houston,AB,11,41,confused
4,5,Eva,45,Phoenix,A,67,46,paranoid