In [1]:
#26  min

In [40]:
import pandas as pd

data = {
    "name": ["Alice", "Shreechan", "Charlie", "David", "Eva", "Ragav", "Shaurav", "Rajiv", "Bibek", "Shanjiv"],
    "age": [25, None, 35, 40, 45, 29, 26, 26, 21, 23],
    "city": ["New York", None, "Chicago", "Houston", "Phoenix", "Dolkha", "Lamjung", "Tanahun", "Lamjung", "Kathmandu"],
    "blood_type": ["A", None, "O", "AB", "A", "B+", "B", "A", "A+", "O+"],
    "exam_marks": [23, None, 23, 11, 67, 43, 76, 23, 65, 22]
    
}
df = pd.DataFrame(data)

1. linear
2. polymonial
3. time

In [41]:
df.interpolate(method="linear", axis= 0, inplace= True)

C:\Users\Byteee\AppData\Local\Temp\ipykernel_19880\1121566326.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", axis= 0, inplace= True)

In [42]:
df['exam_marks'] = df['exam_marks'].interpolate(method='polynomial', order=2)

In [46]:
df['blood_type'].fillna(df['blood_type'].mode().iloc[0], inplace= True, axis = 0)

C:\Users\Byteee\AppData\Local\Temp\ipykernel_19880\360639546.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['blood_type'].fillna(df['blood_type'].mode().iloc[0], inplace= True, axis = 0)

In [43]:
df['city'].fillna(df['city'].mode().iloc[0], inplace=True, axis=0)

C:\Users\Byteee\AppData\Local\Temp\ipykernel_19880\760616962.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna(df['city'].mode().iloc[0], inplace=True, axis=0)

In [44]:
df['age'] = df['age'].interpolate(method='linear')

In [47]:
df

        name   age       city blood_type  exam_marks
0      Alice  25.0   New York          A        23.0
1  Shreechan  30.0    Lamjung          A        23.0
2    Charlie  35.0    Chicago          O        23.0
3      David  40.0    Houston         AB        11.0
4        Eva  45.0    Phoenix          A        67.0
5      Ragav  29.0     Dolkha         B+        43.0
6    Shaurav  26.0    Lamjung          B        76.0
7      Rajiv  26.0    Tanahun          A        23.0
8      Bibek  21.0    Lamjung         A+        65.0
9    Shanjiv  23.0  Kathmandu         O+        22.0

In [49]:
df.sort_values(by="name", ascending=True, inplace=True)

In [50]:
df

        name   age       city blood_type  exam_marks
0      Alice  25.0   New York          A        23.0
8      Bibek  21.0    Lamjung         A+        65.0
2    Charlie  35.0    Chicago          O        23.0
3      David  40.0    Houston         AB        11.0
4        Eva  45.0    Phoenix          A        67.0
5      Ragav  29.0     Dolkha         B+        43.0
7      Rajiv  26.0    Tanahun          A        23.0
9    Shanjiv  23.0  Kathmandu         O+        22.0
6    Shaurav  26.0    Lamjung          B        76.0
1  Shreechan  30.0    Lamjung          A        23.0

In [55]:
df.sort_values(by = "age", ascending = True, inplace = True)

In [56]:
df

        name   age       city blood_type  exam_marks
8      Bibek  21.0    Lamjung         A+        65.0
9    Shanjiv  23.0  Kathmandu         O+        22.0
0      Alice  25.0   New York          A        23.0
7      Rajiv  26.0    Tanahun          A        23.0
6    Shaurav  26.0    Lamjung          B        76.0
5      Ragav  29.0     Dolkha         B+        43.0
1  Shreechan  30.0    Lamjung          A        23.0
2    Charlie  35.0    Chicago          O        23.0
3      David  40.0    Houston         AB        11.0
4        Eva  45.0    Phoenix          A        67.0

In [ ]:
# df["Column name"].mean()
# df["Column name"].sum()
# df["Column name"].min()
# df["Column name"].max()

In [62]:
mean_age = df["age"].mean()
sum_age = df["age"].sum()
min_age = df["age"].min()
max_age = df["age"].max()

In [66]:
df['age']

8    21.0
9    23.0
0    25.0
7    26.0
6    26.0
5    29.0
1    30.0
2    35.0
3    40.0
4    45.0
Name: age, dtype: float64

In [67]:
print(f"mean = {mean_age},\n sum = {sum_age},\n min = {min_age},\n max = {max_age}")

mean = 30.0,
 sum = 300.0,
 min = 21.0,
 max = 45.0