# Pandas Practice Workbook — Netflix Dataset (125 Questions)
**Prepared by Ananda Rimal** · Dataset: `netflix_titles.csv`

**Columns:** `show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description`

**Instructions**
- Write your answer in the code cell **below each question**
- Every answer must be pandas code — no manual counting
- Sections G (GroupBy) and H (Cleaning) may need columns you create along the way — read carefully

| Section | Topic | Questions |
|---------|-------|-----------|
| A | First Analysis of Data | 15 |
| B | Selection with `[]`, `.loc`, `.iloc` | 25 |
| C | Conditions (with `.loc`) | 20 |
| D | Sorting | 10 |
| E | Updating Data | 15 |
| F | GroupBy | 20 |
| G | Cleaning | 20 |
| **Total** | | **125** |

## Section A — First Analysis of Data (Q1–Q15)

#### Q1. Load the dataset into a DataFrame called `df` and display the first 5 rows.

In [ ]:
import pandas as pd
df = pd.read_csv('netflix_titles.csv')

#aaaaaa

#### Q2. Display the **last 7 rows** of the DataFrame.

In [4]:
# Your answer here
df.tail(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### Q3. How many rows and columns does the dataset have?

In [8]:
# Your answer here
df.shape

(8807, 12)

#### Q4. Display the names of all columns.

In [9]:
# Your answer here
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

#### Q5. Use `info()` — which columns have missing values, and what is the data type of each column?

In [10]:
# Your answer here
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### Q6. Use `describe()` on the numeric columns. What is the minimum and maximum `release_year`?

In [11]:
# Your answer here
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

#### Q7. Use `describe(include="object")` on the text columns. Which value appears most often in the `type` column?

In [12]:
# Your answer here
df.describe(include="object")

C:\Users\Byteee\AppData\Local\Temp\ipykernel_16316\2090891308.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

#### Q8. Count the missing values in **every** column with one command.

In [13]:
# Your answer here
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

#### Q9. Which single column has the **most** missing values?

In [ ]:
# Your answer here
a = df.isna().sum()
a.idxmax()

'director'

#### Q10. How many **unique** values are in the `rating` column? Display them.

In [ ]:
# Your answer here
df['rating'].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

#### Q11. Show 5 **random** rows using `sample()`.

In [ ]:
# Your answer here
df.sample()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6544,s6545,Movie,Cult of Chucky,Don Mancini,"Fiona Dourif, Michael Therriault, Adam Hurtig,...",United States,"October 3, 2017",2017,R,90 min,Horror Movies,Following a string of murders in the asylum wh...

#### Q12. What is the memory usage of the DataFrame? (hint: `info()` or `memory_usage()`)

In [ ]:
# Your answer here
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

#### Q13. Display the data type of only the `release_year` column.

In [ ]:
# Your answer here
df['release_year'].dtype

dtype('int64')

#### Q14. Count how many titles are of each `type` using `value_counts()`.

In [ ]:
# Your answer here
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

#### Q15. Check: does the dataset contain any **fully duplicated** rows?

In [5]:
# Your answer here
df.duplicated().sum()

np.int64(0)

## Section B — Selection with `[]`, `.loc`, `.iloc` (Q16–Q40)
*(Q16–Q30: default 0,1,2,... index · Q31–Q40: after `set_index("show_id")`)*

#### Q16. Select the `title` column as a **Series**.

In [7]:
# Your answer here
df['title']

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: str

#### Q17. Select the `title` column as a **DataFrame** (hint: double brackets).

In [10]:
# Your answer here
df[['title']]

                      title
0      Dick Johnson Is Dead
1             Blood & Water
2                 Ganglands
3     Jailbirds New Orleans
4              Kota Factory
...                     ...
8802                 Zodiac
8803            Zombie Dumb
8804             Zombieland
8805                   Zoom
8806                 Zubaan

[8807 rows x 1 columns]

#### Q18. Select the columns `title`, `type`, and `country` together.

In [12]:
# Your answer here
df[['title', 'type', 'country']]

                      title     type        country
0      Dick Johnson Is Dead    Movie  United States
1             Blood & Water  TV Show   South Africa
2                 Ganglands  TV Show            NaN
3     Jailbirds New Orleans  TV Show            NaN
4              Kota Factory  TV Show          India
...                     ...      ...            ...
8802                 Zodiac    Movie  United States
8803            Zombie Dumb  TV Show            NaN
8804             Zombieland    Movie  United States
8805                   Zoom    Movie  United States
8806                 Zubaan    Movie          India

[8807 rows x 3 columns]

#### Q19. Select the first 10 rows using `.iloc`.

In [15]:
# Your answer here
df.iloc[0:10]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

#### Q20. Select rows with labels 10 to 20 using `.loc`. How many rows do you get and why?

In [18]:
# Your answer here
df.iloc[10:21]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,NaN,NaN,"September 22, 2021",2021,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...","In the late 1970s, an accused serial rapist cl..."

#### Q21. Using `.iloc`, select rows at positions 5 to 14 (10 rows). Compare with Q20 — why is the row count logic different?

In [21]:
# Your answer here
df.iloc[5:15,10:20]

,listed_in,description
5,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,"Comedies, Dramas",A woman adjusting to life after a loss contend...
10,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,"Dramas, International Movies",After most of her family is murdered in a terr...
13,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...

#### Q22. Using `.loc`, select rows 0 to 9 with only the columns `title` and `release_year`.

In [ ]:
# Your answer here
df.loc[:9, ['title']]

#.loc for label-based indexing, 
#.iloc for position-based indexing.

                              title
0              Dick Johnson Is Dead
1                     Blood & Water
2                         Ganglands
3             Jailbirds New Orleans
4                      Kota Factory
5                     Midnight Mass
6  My Little Pony: A New Generation
7                           Sankofa
8     The Great British Baking Show
9                      The Starling

#### Q23. Using `.iloc`, select the first 8 rows and the first 5 columns.

In [27]:
# Your answer here
df.iloc[0:8, 0:5]

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ..."
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D..."

#### Q24. Using `.iloc`, select the **last row** of the DataFrame.

In [30]:
# Your answer here
df.iloc[[-1]]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### Q25. Using `.iloc`, select the last 5 rows and the last 2 columns (negative positions).

In [ ]:
# Your answer here

#### Q26. Using `.loc`, get the value of `title` for the row with label 50.

In [ ]:
# Your answer here

#### Q27. Using `.iloc`, get the value in row position 100, column position 2. Which column is that?

In [ ]:
# Your answer here

#### Q28. Using `.iloc`, select every 100th row (hint: slicing with a step `::100`).

In [ ]:
# Your answer here

#### Q29. Using `.loc`, select rows 0 to 4 and **all** columns from `title` to `country` (label slicing on columns!).

In [ ]:
# Your answer here

#### Q30. Select three specific rows by label — 3, 33, and 333 — in one `.loc` call.

In [ ]:
# Your answer here

#### Q31. Set `show_id` as the index of `df` (keep it for the rest of Section B). Display the head.

In [ ]:
# Your answer here

#### Q32. Using `.loc`, select the row with label `"s1"`.

In [ ]:
# Your answer here

#### Q33. Using `.loc`, select rows `"s10"` to `"s15"`. Does label slicing still include the end?

In [ ]:
# Your answer here

#### Q34. Using `.iloc`, select the row at position 0. Is it the same row as label `"s1"`?

In [ ]:
# Your answer here

#### Q35. Using `.loc`, get the `title` and `type` of the show with id `"s500"`.

In [ ]:
# Your answer here

#### Q36. Using `.iloc`, select the row at position 499. Is its label `"s500"`? Explain why or why not in a comment.

In [ ]:
# Your answer here

#### Q37. Using `.loc`, select shows `"s1"`, `"s100"`, and `"s1000"` with columns `title` and `release_year`.

In [ ]:
# Your answer here

#### Q38. What happens if you run `df.loc[0]` now? Try it, read the error, and explain in a comment.

In [ ]:
# Your answer here

#### Q39. Using `.iloc`, select rows at positions [0, 99, 999] in one call.

In [ ]:
# Your answer here

#### Q40. Reset the index back to 0,1,2,... using `reset_index()`. Display the head.

In [ ]:
# Your answer here

## Section C — Conditions with `.loc` (Q41–Q60)
*Write every filter with `df.loc[condition]` or `df.loc[condition, columns]` style where possible.*

#### Q41. Select all rows where `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q42. Select all rows where `type` is `"TV Show"` — show only `title` and `country` using one `.loc` call.

In [ ]:
# Your answer here

#### Q43. Select all titles released in 2021.

In [ ]:
# Your answer here

#### Q44. Select all titles released **before** 2000.

In [ ]:
# Your answer here

#### Q45. Select all titles released between 2015 and 2020 (inclusive) — two conditions with `&`.

In [ ]:
# Your answer here

#### Q46. Select all Movies released after 2019 (two conditions).

In [ ]:
# Your answer here

#### Q47. Select all titles where `rating` is `"TV-MA"`.

In [ ]:
# Your answer here

#### Q48. Select all titles where `rating` is either `"PG"` or `"PG-13"` using `.isin()`.

In [ ]:
# Your answer here

#### Q49. Select all titles where `rating` is **NOT** `"TV-MA"` (hint: `~` or `!=`).

In [ ]:
# Your answer here

#### Q50. Select all titles where `country` is exactly `"India"`.

In [ ]:
# Your answer here

#### Q51. Select all titles where `country` **contains** `"India"` (hint: `str.contains`, use `na=False`). Why is the row count different from the previous question?

In [ ]:
# Your answer here

#### Q52. Select all Movies from the United States — show only `title` and `release_year`.

In [ ]:
# Your answer here

#### Q53. Select all titles where `director` is missing (hint: `isna()`).

In [ ]:
# Your answer here

#### Q54. Select all titles where `director` is **not** missing.

In [ ]:
# Your answer here

#### Q55. Select all TV Shows released in 2020 **or** 2021.

In [ ]:
# Your answer here

#### Q56. Select all titles whose `title` starts with the letter `"A"` (hint: `str.startswith`, `na=False`).

In [ ]:
# Your answer here

#### Q57. Select all titles whose `title` contains the word `"Love"`.

In [ ]:
# Your answer here

#### Q58. Using `.loc` with a condition, show the `title`, `rating`, and `release_year` of all Movies rated `"R"`.

In [ ]:
# Your answer here

#### Q59. Count how many Movies were released after 2015 (condition + `len()` or `.shape`).

In [ ]:
# Your answer here

#### Q60. Challenge: select all Movies that are from India **or** Nepal and released after 2010 — careful with brackets around the `|` condition!

In [ ]:
# Your answer here

## Section D — Sorting (Q61–Q70)

#### Q61. Sort the DataFrame by `release_year` ascending. Show the head — what are the oldest titles?

In [ ]:
# Your answer here

#### Q62. Sort by `release_year` **descending**. Show the 10 newest titles.

In [ ]:
# Your answer here

#### Q63. Sort by `title` alphabetically.

In [ ]:
# Your answer here

#### Q64. Sort by `release_year` descending AND `title` ascending at the same time (list of columns + list of ascending values).

In [ ]:
# Your answer here

#### Q65. Sort by `rating`, and show only `title` and `rating` in the result.

In [ ]:
# Your answer here

#### Q66. Sort the **index** using `sort_index()` (useful after filtering).

In [ ]:
# Your answer here

#### Q67. Show the 5 oldest Movies (filter first, then sort, then head).

In [ ]:
# Your answer here

#### Q68. Show the 5 newest TV Shows.

In [ ]:
# Your answer here

#### Q69. Sort by `country` and put the missing values **first** (hint: `na_position="first"`).

In [ ]:
# Your answer here

#### Q70. What does `ascending=[False, True]` mean when sorting by two columns? Demonstrate with `release_year` and `title` and explain in a comment.

In [ ]:
# Your answer here

## Section E — Updating Data (Q71–Q85)

#### Q71. Rename the column `listed_in` to `genres` (keep this change).

In [ ]:
# Your answer here

#### Q72. Create a new column `age_years` = 2026 minus `release_year`.

In [ ]:
# Your answer here

#### Q73. Create a column `is_movie` that is `True` when `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q74. Create a column `is_recent` that is `True` when `release_year >= 2020`.

In [ ]:
# Your answer here

#### Q75. Using `.loc` with a condition, set `rating` to `"UNRATED"` for all rows where `rating` is missing.

In [ ]:
# Your answer here

#### Q76. Replace the value `"United States"` with `"USA"` in the `country` column (hint: `replace`).

In [ ]:
# Your answer here

#### Q77. Convert all titles to UPPERCASE into a new column `title_upper` (hint: `str.upper`).

In [ ]:
# Your answer here

#### Q78. Create a column `title_length` = number of characters in each title (hint: `str.len`).

In [ ]:
# Your answer here

#### Q79. Using `.loc`, change the `title` of the row with index label 0 to `"My Favourite Show"`. Display that row to confirm.

In [ ]:
# Your answer here

#### Q80. Add a column `platform` where every row has the value `"Netflix"`.

In [ ]:
# Your answer here

#### Q81. Delete the column `title_upper` using `drop`.

In [ ]:
# Your answer here

#### Q82. Change `release_year` to type `int32` using `astype`. Check with `dtypes`.

In [ ]:
# Your answer here

#### Q83. Using `.loc` with a condition, create/overwrite a column `era` = `"old"` for titles before 2010 and `"new"` for 2010 onward (two `.loc` assignments, or `np.where`).

In [ ]:
# Your answer here

#### Q84. Increase `age_years` by 1 for **all** rows in one operation.

In [ ]:
# Your answer here

#### Q85. Explain in a markdown comment: why is `df.loc[condition, "col"] = value` the SAFE way to update, instead of `df[condition]["col"] = value`? (SettingWithCopyWarning!)

In [ ]:
# Your answer here

## Section F — GroupBy (Q86–Q105)

#### Q86. Group by `type` and count the number of titles in each group (`size()`).

In [ ]:
# Your answer here

#### Q87. Group by `rating` and count titles. Which rating is most common?

In [ ]:
# Your answer here

#### Q88. Group by `release_year` and count titles. Which year had the most releases?

In [ ]:
# Your answer here

#### Q89. Group by `type` and find the **minimum** and **maximum** `release_year` for each (hint: `agg(["min","max"])`).

In [ ]:
# Your answer here

#### Q90. Group by `type` and compute the **average** `age_years`.

In [ ]:
# Your answer here

#### Q91. Group by `country` and count titles — show only the top 10 (sort + head).

In [ ]:
# Your answer here

#### Q92. Group by `rating` and compute the average `title_length`.

In [ ]:
# Your answer here

#### Q93. Group by `era` (from Q83) and count Movies vs TV Shows (hint: group by TWO columns).

In [ ]:
# Your answer here

#### Q94. Group by `type` and `rating` together and count. Display the result with `unstack()`.

In [ ]:
# Your answer here

#### Q95. For Movies only: group by `release_year` and count — how many movies came out each year since 2015? (filter first, then group, then `.tail()`)

In [ ]:
# Your answer here

#### Q96. Group by `country` and compute the average `release_year` — which 5 countries have the 'newest' catalogs on average? (sort descending, head)

In [ ]:
# Your answer here

#### Q97. Use `value_counts()` on `genres` — why does this NOT give clean genre counts? Explain in a comment (hint: multiple genres in one cell).

In [ ]:
# Your answer here

#### Q98. Group by `is_recent` and count — how many recent vs old titles?

In [ ]:
# Your answer here

#### Q99. Group by `type` and use `.agg()` with a dictionary: count of `title` and mean of `age_years` in ONE command.

In [ ]:
# Your answer here

#### Q100. Group by `rating` and show the **number of unique countries** per rating (hint: `nunique`).

In [ ]:
# Your answer here

#### Q101. Using `groupby` + `head(1)`, show the FIRST title (by current order) in each `type` group.

In [ ]:
# Your answer here

#### Q102. Group by `release_year` and count, then plot it with `.plot()` (line chart). What trend do you see?

In [ ]:
# Your answer here

#### Q103. Group by `year_added`-style logic isn't possible yet — `date_added` is still text! Group by the **first 4 characters trick is wrong**. Explain in a comment why we need Section G (Cleaning) before we can group by the year a title was ADDED.

In [ ]:
# Your answer here

#### Q104. Group by `type` and compute the **median** `release_year`.

In [ ]:
# Your answer here

#### Q105. Challenge: for each `rating`, what percentage of titles are Movies? (hint: group by rating, compute the mean of `is_movie`, multiply by 100)

In [ ]:
# Your answer here

## Section G — Cleaning (Q106–Q125)

#### Q106. Re-check missing values per column (things changed since Section A!).

In [ ]:
# Your answer here

#### Q107. Fill missing `director` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q108. Fill missing `cast` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q109. Fill missing `country` values with the **most common** country (hint: `mode()[0]`).

In [ ]:
# Your answer here

#### Q110. Count the rows where `date_added` is missing, then drop those rows.

In [ ]:
# Your answer here

#### Q111. `date_added` has extra spaces in some rows — strip them (hint: `str.strip`).

In [ ]:
# Your answer here

#### Q112. Convert `date_added` to datetime with `pd.to_datetime`. Check the dtype after.

In [ ]:
# Your answer here

#### Q113. NOW create `year_added` = `.dt.year` and `month_added` = `.dt.month_name()`.

In [ ]:
# Your answer here

#### Q114. Group by `year_added` and count — which year did Netflix add the most content? (This is the question F103 could not answer!)

In [ ]:
# Your answer here

#### Q115. Group by `month_added` and count — which month is most popular for adding content?

In [ ]:
# Your answer here

#### Q116. Look at the `duration` column with `unique()` (first 20 values) — what TWO different formats do you see?

In [ ]:
# Your answer here

#### Q117. Extract the number from `duration` into a new column `duration_int` (hint: `str.extract(r"(\\d+)")` then `astype(float)`).

In [ ]:
# Your answer here

#### Q118. For Movies only: what is the average, minimum, and maximum duration in minutes?

In [ ]:
# Your answer here

#### Q119. For TV Shows only: how many have more than 5 seasons? Show their titles.

In [ ]:
# Your answer here

#### Q120. Check duplicated **titles** (not full rows): are there any titles that appear more than once? Display them.

In [ ]:
# Your answer here

#### Q121. Are those duplicated titles real duplicates or different shows? Inspect a few with `.loc` and explain in a comment.

In [ ]:
# Your answer here

#### Q122. The `rating` column contains some WRONG values that are actually durations (like `"74 min"`) — find them (hint: `str.contains("min", na=False)`).

In [ ]:
# Your answer here

#### Q123. Fix those wrong rating rows: set their `rating` to `"UNRATED"` using `.loc`.

In [ ]:
# Your answer here

#### Q124. Final check: run `info()` and `isna().sum()` — is the dataset clean now? Summarize what you fixed in a comment.

In [ ]:
# Your answer here

#### Q125. Save your cleaned DataFrame to a new file `netflix_clean.csv` (without the index). This file is your submission proof!

In [ ]:
# Your answer here

---
## Submission
- Answer **all 125 questions** — partial answers get partial marks
- Run All must work top to bottom without errors (−5 marks if it crashes)
- Submit BOTH files: `YourName_workbook.ipynb` and `netflix_clean.csv`