In [25]:
import pandas as pd

data = {
    "name": ["Alice", None, "Charlie", "David", "Eva", "Ragav", "Shaurav", "Rajiv", "Bibek", "Shanjiv"],
    "age": [25, None, 35, 40, 45, 29, 26, 26, 21, 23],
    "city": ["New York", None, "Chicago", "Houston", "Phoenix", "Dolkha", "Lamjung", "Tanahun", "Lamjung", "Kathmandu"],
    "blood_type": ["A", None, "O", "AB", "A", "B+", "B", "A", "A+", "O+"],
    "exam_marks": [23, None, 23, 11, 67, 43, 76, 23, 65, 22]
    
}
df = pd.DataFrame(data)

In [24]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks']]

      name   age       city blood_type  exam_marks
0    Alice  25.0   New York          A        23.0
2  Charlie  35.0    Chicago          O        23.0
3    David  40.0    Houston         AB        11.0
4      Eva  45.0    Phoenix          A        67.0
5    Ragav  29.0     Dolkha         B+        43.0
6  Shaurav  26.0    Lamjung          B        76.0
7    Rajiv  26.0    Tanahun          A        23.0
8    Bibek  21.0    Lamjung         A+        65.0
9  Shanjiv  23.0  Kathmandu         O+        22.0

In [27]:
removed = df.dropna(axis=0, inplace=True)

In [21]:
df.columns

Index(['name', 'age', 'city', 'blood_type', 'exam_marks'], dtype='object')

In [23]:
df[['name', 'age', 'city', 'blood_type', 'exam_marks']]

      name   age       city blood_type  exam_marks
0    Alice  25.0   New York          A        23.0
2  Charlie  35.0    Chicago          O        23.0
3    David  40.0    Houston         AB        11.0
4      Eva  45.0    Phoenix          A        67.0
5    Ragav  29.0     Dolkha         B+        43.0
6  Shaurav  26.0    Lamjung          B        76.0
7    Rajiv  26.0    Tanahun          A        23.0
8    Bibek  21.0    Lamjung         A+        65.0
9  Shanjiv  23.0  Kathmandu         O+        22.0